name: Masters
channels:
  - conda-forge/label/cf202003
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - ca-certificates=2019.11.28
  - cartopy=0.18.0
  - certifi=2021.5.30
  - cffi=1.14.5
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - geos=3.8.0
  - glib=2.68.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=4.5.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kaleido-core=0.2.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - mathjax=2.7.7
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nodejs=12.4.0
  - notebook=6.4.0
  - nspr=4.30
  - nss=3.65
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.14.0.1
  - pandocfilters=1.4.2
  - parso=0.8.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=20.2.4
  - plotly=4.14.3
  - proj=6.2.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-kaleido=0.2.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.0
  - retrying=1.3.3
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=50.3.0
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.5
  - terminado=0.10.0
  - testpath=0.5.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - affine==2.3.0
    - alembic==1.6.5
    - astunparse==1.6.3
    - autokeras==1.0.13
    - beautifulsoup4==4.9.3
    - branca==0.4.2
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==7.1.2
    - click-plugins==1.1.1
    - cliff==3.8.0
    - cligj==0.7.1
    - cmaes==0.8.2
    - cmd2==1.5.0
    - colorama==0.4.4
    - colorlog==5.0.1
    - contextily==1.1.0
    - convertbng==0.6.25
    - descartes==1.1.0
    - fiona==1.8.19
    - flatbuffers==1.12
    - folium==0.12.1
    - future==0.18.2
    - gast==0.4.0
    - geographiclib==1.50
    - geopandas==0.9.0
    - geoplot==0.4.1
    - geopy==2.1.0
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - greenlet==1.1.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==2.10
    - influxdb-client==1.18.0
    - joblib==1.0.1
    - kaggle==1.5.12
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - keras-tuner==1.0.2
    - libpysal==4.4.0
    - lightgbm==3.2.1
    - mako==1.1.4
    - mapclassify==2.4.2
    - markdown==3.3.4
    - matplotlib-venn==0.11.6
    - mercantile==1.2.1
    - momepy==0.4.4
    - munch==2.5.0
    - networkx==2.5.1
    - numpy==1.20.3
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - optuna==2.7.0
    - osgridconverter==0.1.3
    - osmnx==1.1.1
    - pandas==1.2.4
    - pbr==5.6.0
    - prettytable==2.1.0
    - protobuf==3.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybng==0.1.8
    - pygeos==0.10
    - pyperclip==1.8.2
    - pyproj==3.1.0
    - python-editor==1.0.4
    - python-slugify==5.0.2
    - pyyaml==5.4.1
    - rasterio==1.2.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - rtree==0.9.7
    - rx==3.2.0
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - simdkalman==1.0.1
    - snuggs==1.4.7
    - soupsieve==2.2.1
    - sqlalchemy==1.4.15
    - stevedore==3.3.0
    - tabulate==0.8.9
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - terminaltables==3.1.0
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - tqdm==4.61.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - xgboost==1.4.2
